### ISSUE TITLE
Suspected T18 sample not flagged (Warning) correctly

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#217] opened 2022-02-25 09:05 UTC
2022-04403-06 is only flagged with a yellow color in the summary table for some reason? This is not in agreement with the rules. It's very important that the suspected trisomy samples are correctly flagged with  warnings

**Comment by alieden** [comment] 2022-02-25 09:07
![image](https://user-images.githubusercontent.com/22740092/155687211-bbad4786-68a3-48c1-9a36-28153b70ffe2.png)

**Comment by henrikstranneheim** [comment] 2022-02-25 09:11
@mayabrandi Could you investigate if this is bug?

**Comment by elevu** [comment] 2022-02-25 09:33
For the backenders, the color of the cell is based on the `sample.warnings` object. If it is 'warning' it is yellow, if it 'danger' it is red. Not sure if there is something that should be different.

**Comment by mayabrandi** [comment] 2022-03-03 14:33
Ill have a look at this

**Comment by alieden** [comment] 2022-03-09 10:16
I have another example. Search for the sample 2021-34971 and you'll see the data from the two runs have different warnings although they should produce the same warning since the z-score is >=4.0 (the correct warning is given for aliq 05).

**Comment by mayabrandi** [comment] 2022-03-09 10:22
I will investigate this tomorow.

**Comment by mayabrandi** [comment] 2022-03-10 12:18
This is not a bug, but intended. 

The color is orange if: 

fetal_fraction_pf < preface_threshold and (z_score >= soft_max or z_score <= hard_min)

preface_threshold= 4
soft_max= 3
hard_min= -8

The orange wanring color doesnt give a warning message in the warning column. 

1) Do you want to keep the rule abouve using soft_max, resulting in orange warning color?
2) If yes, do you want to have a text message in the warning column also in these cases?

**Comment by mayabrandi** [comment] 2022-03-10 12:21
Code to change depending on Agnes answer:

https://github.com/Clinical-Genomics/statina/blob/c16a28118e916b2038f5109c791d6d2a44814436/statina/models/server/sample.py#L210

https://github.com/Clinical-Genomics/statina/blob/c16a28118e916b2038f5109c791d6d2a44814436/statina/models/server/sample.py#L175

**Comment by alieden** [comment] 2022-03-10 13:32
I want the rules to match the following figure. I've tried to make it clearer. Let me know if it is still unclear
![Z-score_rule](https://user-images.githubusercontent.com/22740092/157672155-96ce8e22-35fa-4f4c-abb3-e527ca2dfa1d.png)
.

**Comment by mayabrandi** [comment] 2022-03-14 10:43
This is fixed now

**Closed by mayabrandi** 2022-03-14 10:43 UTC
Labels: bug, High prio
