### ISSUE TITLE
Not possible to save sample info in batch 2119420_3_NIPT (medium priority)

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/statina#174] opened 2021-11-24 14:12 UTC
It's not possible to save sample related information (and include samples) for this "problem batch" with reruns etc

**Comment by mayabrandi** [comment] 2021-11-25 12:58
Hi! 

So the problem is that the same batch has been uploaded three times with different naming 2119420_NIPT, 2119420_2_NIPT, 2119420_3_NIPT. --> the samples in the batch are uploaded 3 times. 

The question is what you want..

The whole statina is designed with the assumption that sample-names are unique. We chan change that assumption if you want to be able to have several analysis up for the same sample, but then we need to do some changes to the code.

Or you don't want several versions of the same batch in the database? But actually want the old batches to be deleted? Then we should do some logic and error handling for situations when you are trying to upload a sample with a name that's all-ready in the database. Probably the upload should fail then. 

 Those are my thoughts. What do you say? @alieden @Mropat

**Comment by Mropat** [comment] 2021-11-25 14:04
@alieden 
To add to this: the practice of uploading samples with the same filename has occurred in the past also, for example when you spike-in an old positive sample as a control into a batch. All such samples cannot be included into plots twice currently

**Comment by alieden** [comment] 2021-11-26 14:06
If we run a plasma sample from the same blood tube twice the samples should end differently for example 2021-20321-03 and 2021-20321-04. However, if a library pool is resequenced or reanalyzed, which has happened a bit more than expected, the sample names will be the same of course. From our perspective and traceability I think it would be best to be able to have all run data in Statina but it's nothing that is of major importance, it could be enough to get the full batch archive for the runs that are removed from Statina. So I'll let you decide based on the above and how much of an effort it is to change...

**Comment by mayabrandi** [comment] 2021-11-26 14:15
A batch removed from satatina=the batch being removed from the database!

**Comment by mayabrandi** [comment] 2021-11-26 14:19
So if you want to be able to look at reruns of the same batch in any way, we need to allow duplication of sample names in the database. Which is all-right. I just wanted to double check thats what you wanted.

**Comment by Mropat** [comment] 2021-11-26 17:54
@mayabrandi @alieden the samples uoloaded with non-unique names still will not be able to be included in plots

**Comment by mayabrandi** [comment] 2021-11-29 07:30
I don't see why they wouldn’t. Lets have a chat later today and you can explain how you think @Mropat

**Comment by elevu** [comment] 2022-01-27 09:36
Duplicate of https://github.com/Clinical-Genomics/statina/issues/181

**Closed by elevu** 2022-01-27 09:36 UTC
Labels: backend
